### ISSUE TITLE
Cleanly shutting down

### ISSUE THREAD

**Issue by tombentley** [EnMasseProject/amqp-kafka-bridge#70]
The bridge doesn't set any shutdown hooks, so in the event of the process receiving SIGINT (Ctrl+C) or similar the program will exit without necessarily executing any `finally` blocks, calling `close()` etc. Presumably this could lead to loss of messages.

**Comment by ppatierno** [comment]
Agree. At same time without closing Kafka consumers in a clean way, the broker could take more time to start a rebalance for partitions.

**Comment by tombentley** [comment]
Some experimentation reveals that Spring sets up a shutdown hook which calls `Application.stop()`, so we should exit cleanly in the event of SIGINT.
